server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
   active:
    - "qa"

build:
 version: "17.2"

loans:
  message: "Welcome to loans related local apis"
  contactDetails:
   name: "Gurpreet Singh -Developer"
   email: "er.gurdevloans@yahoo.com"
  onCallSupport:
   - 3333333333
   - 4444444444