spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related Prod apis"
  contactDetails:
    name: "Gurpreet Singh- PROD"
    email: "gurpreet.tsys.aws@gmail.com"
  onCallSupport:
    - 8929014411
    - 8929014411